Cleanups, use ggezs timer
red-life-project/red-life pull request #179
Opened 2022-12-04 15:35 UTC by Nereuxofficial

2022-12-04 15:40 UTC, SanderForGodot requested changes
Add import back

2022-12-04 15:40 UTC, SanderForGodot commented on game/src/main.rs
> -use ggez::conf::FullscreenType;
Ich glaube CI failed weil der removed wurde

Clippy zeigt den als unused aber wir brauchen ihn

2022-12-04 15:41 UTC, Nereuxofficial commented on game/src/main.rs
> -use ggez::conf::FullscreenType;
Jup, war ausversehen. Danke!

2022-12-05 10:45 UTC, Flippchen approved these changes
LGTM

2022-12-05 10:50 UTC, MarionHinkel approved these changes
LGTM

2022-12-05 10:51 UTC, merged