Add translations
red-life-project/red-life pull request #272
Opened 2022-12-27 19:33 UTC by Eraden

2022-12-28 14:24 UTC, Nereuxofficial commented
Hey, thank you so much for implementing this! We really appreciate it. It looks good except for the holes being in a broken state and their indicator being present because our check for them is really primitive. I will review it in the following days :)

2022-12-30 21:23 UTC, Nereuxofficial requested changes
The Pull Request looks great apart from a few minor issues and you can merge it once those are fixed:
- The English IntroScreen has Text that overruns to the right
- Some Internal Code sadly depends on the names of the Machines(due to time constraints in the project). So in event.rs Line 164 and in generate_machines.rs Line 34 we use kanguage-dependent variables so changing the language changes the behaviour.

Again thank you for taking the time to implement this

2022-12-30 21:23 UTC, Nereuxofficial commented on game/src/languages/german.rs
> +pub const COMETA_STRIKE: [&str; 2] = [
COMET_STRIKE*

2023-01-01 14:13 UTC, Eraden commented
Hi, I think I solved all issues here but unfortunately this ends up being huge PR

Here is what I did:

* Strings where replaces with enum for Machine and Trade, additionally this should prevent some problems with unmatched name and is a little bit faster
* Hash maps have capacity since overflowing then is really slow and requires rehashing every key
* Into screen was fixed
* Typos where removed

2023-01-01 15:44 UTC, Nereuxofficial commented
> Note:
>
> Some inline attributes where removed. Be careful with them and note they are not c++ inline, they are only useful in libraries since they are instruction for compiler this part should be inline in user application not in current library

Ah so inlining is only useful for usage across crate boundaries. Thanks for pointing that out

2023-01-01 15:45 UTC, Nereuxofficial approved these changes
LGTM

2023-01-02 15:58 UTC, Eraden commented
Hi, I can't merge or sign reviewer.

Additionally I created couple issues

2023-01-02 22:31 UTC, merged