Delete Saves reworked
red-life-project/red-life pull request #92
Opened 2022-11-21 16:02 UTC by leoschnuell

Hoffentlich ist es diesmal besser

2022-11-21 23:36 UTC, Nereuxofficial requested changes
Sieht schon gut aus, änder noch die Kleinigkeiten und dann passt das

2022-11-21 23:36 UTC, Nereuxofficial commented on game/src/backend/gamestate.rs
> +        for entry in existing_files.unwrap() {
Das schöne an RLResult ist, dass wir nicht .unwrap() callen müssen, wir können mit ? einen Error returnen wenn es einen Error returnen würde, ansonsten wird es quasi ,,geunwrapt"

2022-11-21 23:36 UTC, Nereuxofficial commented on game/src/backend/gamestate.rs
> +        for entry in existing_files.unwrap() {
und das können wir für jedes .unwrap() oder expect hier machen, so ermöglichen wir schönes Error-handling

2022-11-21 23:36 UTC, Nereuxofficial commented on game/src/backend/gamestate.rs
> +        return Ok(());
wir können in dieser Zeile nur Ok(()) schreiben, weil wir in Rust das return nicht brauchen, wenn wir das Semicolon weglassen

2022-11-21 23:36 UTC, Nereuxofficial commented on game/src/main_menu/mainmenu.rs
> +                    GameState::delete_saves().expect("all saves to be deleted");
hier nochmal dasselbe, einfach durch ? ersetzen

2022-11-23 19:30 UTC, Nereuxofficial requested changes
Da sind noch zwei unwraps drin und ich kanns nicht mergen grade, fix das kurz noch und dann funktioniert's

2022-11-24 10:43 UTC, Flippchen requested changes
Add Logging Statement

2022-11-24 10:51 UTC, Nereuxofficial approved these changes
LGTM

2022-11-24 11:16 UTC, Flippchen approved these changes
LGTM

2022-11-24 11:17 UTC, Nereuxofficial approved these changes
LGTM

2022-11-24 11:18 UTC, merged